[SERVICE]
    Flush          1
    Grace          5
    Daemon         Off
    Log_Level      info
    storage.path   /opt/pi-guard-lite/data/fluent-bit

[INPUT]
    Name           tail
    Path           /var/log/auth.log
    Tag            auth.log
    Path_Key       path
    DB             /opt/pi-guard-lite/data/fluent-bit/auth.db
    Read_from_Head true
    Skip_Long_Lines On

[INPUT]
    Name           tail
    Path           /var/log/syslog
    Tag            syslog
    Path_Key       path
    DB             /opt/pi-guard-lite/data/fluent-bit/syslog.db
    Read_from_Head true
    Skip_Long_Lines On

[INPUT]
    Name           tail
    Path           /var/log/nginx/access.log
    Tag            nginx.access
    Path_Key       path
    DB             /opt/pi-guard-lite/data/fluent-bit/nginx_access.db
    Read_from_Head true
    Skip_Long_Lines On

[INPUT]
    Name           tail
    Path           /var/log/nginx/error.log
    Tag            nginx.error
    Path_Key       path
    DB             /opt/pi-guard-lite/data/fluent-bit/nginx_error.db
    Read_from_Head true
    Skip_Long_Lines On

[OUTPUT]
    Name           stdout
    Match          *
    Format         json_lines
